// promise.then(f1).catch(f2);
// promise.then(f1, f2);

//они разные в первом случае f2 сработает при ошибке, во втором случае выполнится f2 при успехе то есть ошибка не обработана